name: Deploy to GHCR.IO
on:
  workflow_run:
    workflows: [Code Standards, Tests]
    branches: [master]
    types: 
      - completed
    
jobs:
  push-to-registry:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    concurrency:
      group: registry-push-master
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      # Log in to the GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/stripewebhook:latest .

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/stripewebhook:latest